main/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from blog import views as blog_views
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_views.PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>/', blog_views.PostDetailView.as_view(), name='post-detail'),
    path('post/new/', blog_views.PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', blog_views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', blog_views.PostDeleteView.as_view(), name='post-delete'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    image = models.ImageField(upload_to='posts')
    caption = models.TextField(max_length=300)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.author.username} Post'

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')
    bio = models.TextField(max_length=150)

    def __str__(self):
        return f'{self.user.username} Profile'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': "validate", 'type': "email", 'id': "email"}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': "validate", 'type': "email", 'id': "email"}))

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'bio']

blog/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (ListView, DetailView,
                                  CreateView, UpdateView,
                                  DeleteView)
from .models import Post
from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    context = {
        'posts': Post.objects.filter(author=request.user)
    }
    return render(request, 'blog/home.html', context)


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = Post.objects.filter(author=self.request.user)
        return queryset.order_by('-date_posted')


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

    def get_queryset(self):
        queryset = Post.objects.filter(author=self.request.user)
        return queryset


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['image', 'caption']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['image', 'caption']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

users/views.py
from django.shortcuts import render, redirect
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            return redirect('profile')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form, 'title': 'Sign Up'})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link
            href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
            rel="stylesheet"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'blog/css/main.min.css' %}">
    <link rel="shortcut icon" href="{% static 'blog/res/favicon.ico' %}" type="image/x-icon"/>
    {% if title %}
        <title>Seed - {{ title }}</title>
    {% else %}
        <title>Seed</title>
    {% endif %}
</head>
{% block content %}
{% endblock content %}
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
    <body id="home">
        <div class="container h-100">
            <!--Navigation icons-->
            <div class="row justify-content-center">
                <div class="col-lg-10 col-md-12 mx-auto">
                    <div class="nav-icons d-flex flex-wrap justify-content-end mt-4">
                        <a href="{% url 'post-create' %}" title="Create post"><i class="material-icons-outlined">
                            add_box
                        </i>
                        </a>
                        <a href="{% url 'profile' %}" title="Settings"><i class="material-icons-outlined">
                            settings
                        </i></a>
                        <a href="{% url 'logout' %}" title="Sign out"><i class="material-icons-outlined">
                            exit_to_app
                        </i></a>
                    </div>
                </div>
            </div>
            <!--Profile Details-->
            <div class="row justify-content-center">
                <div class="col-lg-10 col-md-12 mx-auto">
                    <div class="profile justify-content-start flex-wrap d-flex mt-2">
                        <img class="avatar" src="{{ user.profile.image.url }}" alt="Profile Image"/>
                        <div class="info ml-5 mt-3">
                            <h3 id="name" class="font-weight-bold">
                                <a href="{% url 'blog-home' %}">{{ user.username }}'s Family</a>
                            </h3>
                            <p class="bio">
                                {{ user.profile.bio }}
                            </p>
                            <span><a href="/" class="font-weight-bold">{{ posts.count }}</a> memories</span>
                        </div>
                    </div>
                </div>
            </div>
            <!--Posts-->
            <div class="row justify-content-center align-items-center">
                <div class="col-lg-10">
                    <div class="posts text-center d-flex flex-wrap mt-5 px-2">
                        {% for post in posts %}
                            <div class="col-lg-4">
                                <div class="card shadow-sm">
                                    <div class="thumbnail">
                                        <img src="{{ post.image.url }}" alt="Post"/>
                                    </div>
                                    <div class="date my-2">
                                        <a href="{% url 'post-detail' post.id %}">{{ post.date_posted|date:"j M Y" }}</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'blog/js/materialize.min.js' %}"></script>
    </body>

{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
    <body id="password-reset">
        <div class="container h-100">
            <div class="row h-100 mx-auto justify-content-center align-items-center">
                <div class="col-lg-4 col-md-12">
                    <div class="card my-2">
                        <img src="{% static 'blog/res/flame-delete-confirmation.png' %}" alt="password changed"
                             class="card-img-top mx-auto">
                        <div class="card-body p-2 px-4">
                            <div class="text my-4">
                                <h5>Are you sure?</h5>
                                <h6 class="light-text">Once you delete this post, it will be gone forever.</h6>
                            </div>
                            <div class="inputs text-capitalize justify-content-between lower d-flex flex-wrap">
                                <form method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-orange  text-capitalize">
                                        yes, delete
                                    </button>
                                </form>
                                <a href="{% url 'post-detail' object.id %}" class="btn btn-grey  text-capitalize">
                                    no, cancel
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'blog/js/materialize.min.js' %}"></script>

    </body>

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
    <body id="post-detail">
        <div class="container h-100">
            <!--Navigation-->
            <div class="row justify-content-center">
                <div class="col-lg-10 col-md-12 mx-auto">
                    <div class="nav-icons d-flex flex-wrap justify-content-end mt-4">
                        <a href="{% url 'blog-home' %}" title="Home"><i class="material-icons-outlined">
                            home
                        </i>
                        </a>
                        <a href="{% url 'post-create' %}" title="Create post"><i class="material-icons-outlined">
                            add_box
                        </i>
                        </a>
                        <a href="{% url 'profile' %}" title="Settings"><i class="material-icons-outlined">
                            settings
                        </i></a>
                        <a href="{% url 'logout' %}" title="Sign out"><i class="material-icons-outlined">
                            exit_to_app
                        </i></a>
                    </div>
                </div>
            </div>
            <!--Post Details-->
            <div class="row justify-content-center align-items-center">
                <div class="col-lg-8 col-md-12">
                    <div class="details mt-2">
                        <div class="card p-3 shadow-sm">
                            <div class="row px-2 mb-2 justify-content-between">
                                <a href="{% url 'post-delete' object.id %}" title="Delete"><i
                                        class="material-icons-outlined px-2">
                                    delete
                                </i></a>
                                <a href="{% url 'post-update' object.id %}" title="Update"><i
                                        class="material-icons-outlined px-2">
                                    edit
                                </i></a>
                            </div>
                            <img src="{{ object.image.url }}" class="card-img-top" alt="Post">
                            <div class="card-body px-0">
                                <h6 class="blue font-weight-bold date">{{ object.date_posted|date:"j M Y" }}</h6>
                                <p class="caption m-0 p-2">{{ object.caption }}</p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'blog/js/materialize.min.js' %}"></script>
    </body>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
    <body id="create-post">
        <div class="container h-100">
            <div class="row h-100 mx-auto justify-content-center align-items-center">
                <div class="col-lg-4 col-md-12">
                    <div class="card my-2">
                        <div class="card-body p-2">
                            <!--Button-->
                            <div class="row px-2 justify-content-end">
                                <a href="{% url 'blog-home' %}" title="Cancel"><i class="material-icons-outlined px-2">
                                    cancel
                                </i></a>
                            </div>
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row justify-content-center">
                                    <div class="upload-image text-capitalize">
                                        <button class="btn btn-grey">Choose Image</button>
                                        <div style="opacity: 0;top: 0; position:absolute;left: 0;">{{ form.image }}</div>
                                    </div>
                                </div>
                                <!--Thumbnail-->
                                <div class="row justify-content-center">
                                    {% if post.image %}
                                        <img src="{{ post.image.url }}" alt="Upload Image" id="image">
                                        {% else %}
                                        <img src="{% static 'blog/res/biology.svg' %}" alt="Upload Image" id="image">
                                    {% endif %}

                                </div>
                                <!--Inputs-->
                                <div class="inputs text-capitalize px-4">
                                    <div class="input-field">
                                        <i class="material-icons-outlined prefix">
                                            edit
                                        </i>
                                        {{ form.caption }}
                                        <label for="id_caption">caption</label>
                                    </div>
                                    <button type="submit" class="text-capitalize btn btn-yellow w-100">
                                        post
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'blog/js/materialize.min.js' %}"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('input#input_text, textarea#id_caption').characterCounter();
            });

            window.onload = function () {
                const element = document.getElementById("id_caption");
                element.className = "materialize-textarea";
                element.setAttribute("data-length", "300");
            };

            function readURL(input) {
                if (input.files && input.files[0]) {
                    const reader = new FileReader();

                    reader.onload = function (e) {
                        $('#image').attr('src', e.target.result);
                    };

                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#id_image").change(function () {
                readURL(this);
            });
        </script>
{% endblock content %}

users/templates/users/password_reset.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
    <body id="password-reset">
        <div class="container h-100">
            <div class="row h-100 mx-auto justify-content-center align-items-center">
                <div class="col-lg-4 col-md-12">
                    <div class="card my-2">
                        <img src="{% static 'blog/res/page-not-found-4.png' %}" alt="reset password"
                             class="card-img-top mx-auto">
                        <div class="card-body p-2 px-4">
                            <div class="text my-4">
                                <h5>Forgot password?</h5>
                                <h6 class="light-text">Enter the email associated <br> with your account.</h6>
                            </div>
                            <div class="inputs text-capitalize">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="input-field">
                                        <i class="material-icons-outlined prefix">
                                            email
                                        </i>
                                        {{ form.email }}
                                        <label for="email">email</label>
                                    </div>
                                    <button type="submit" class="btn btn-darkblue w-100 text-capitalize">
                                        reset password
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'blog/js/materialize.min.js' %}"></script>
    </body>
{% endblock content %}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
    <body id="edit-profile">
        <div class="container h-100">
            <!--Profile-->
            <div class="row h-100 mx-auto justify-content-center align-items-center">
                <div class="col-lg-4 col-md-12 mx-auto">
                    <div class="card my-2">
                        <div class="card-body p-2">
                            <!--Button-->
                            <div class="row px-2 justify-content-end">
                                <a href="{% url 'blog-home' %}" title="Cancel"><i class="material-icons-outlined px-2">
                                    cancel
                                </i></a>
                            </div>
                            <!--Avatar-->
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row justify-content-center">
                                    <img src="{{ user.profile.image.url }}" alt="Avatar" id="image">
                                </div>
                                <!--Change Avatar-->
                                <div class="row justify-content-center">
                                    <div class="change-avatar mt-3 text-capitalize">
                                        <button class="btn btn-grey">Change Avatar</button>
                                        <div style="opacity: 0;top: 0; position:absolute;left: 0;">{{ p_form.image }}</div>
                                    </div>
                                </div>
                                <!--Inputs-->
                                <div class="inputs text-capitalize py-2 px-4">
                                    <div class="input-field">
                                        {{ u_form.username }}
                                        <label for="username">username</label>
                                        <div class="text-danger small text-center">
                                            {{ u_form.username.errors }}
                                        </div>
                                    </div>
                                    <div class="input-field">
                                        {{ u_form.email }}
                                        <label for="email">email</label>
                                        <div class="text-danger small text-center">
                                            {{ u_form.email.errors }}
                                        </div>
                                    </div>
                                    <div class="input-field">
                                        {{ p_form.bio }}
                                        <label for="bio">bio</label>
                                        <div class="text-danger small text-center">
                                            {{ p_form.bio.errors }}
                                        </div>
                                    </div>
                                    <button type="submit" class="text-capitalize btn btn-blue w-100">
                                        update profile
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'blog/js/materialize.min.js' %}"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('input#input_text, textarea#id_bio').characterCounter();
            });

            window.onload = function () {
                const element = document.getElementById("id_bio");
                element.className = "materialize-textarea";
                element.setAttribute("data-length", "150");
            };

            function readURL(input) {
                if (input.files && input.files[0]) {
                    const reader = new FileReader();

                    reader.onload = function (e) {
                        $('#image').attr('src', e.target.result);
                    };

                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#id_image").change(function () {
                readURL(this);
            });
        </script>
    </body>
{% endblock content %}